symbols: list[list[str]] = [
    ["`", ["backtick", "backquote", "grave accent"]],
    ["~", ["tilde"]],
    ["!", ["exclamation mark", "exclamation point"]],
    ["@", ["at symbol", "at sign", "at"]],
    ["#", ["pound", "number", "hashtag"]],
    ["$", ["dollar"]],
    ["%", ["percent", "mod\\modulo"]],
    ["^", ["caret", "hat", "exponent"]],
    ["&", ["ampersand", "and"]],
    ["*", ["asterisk", "star"]],
    ["(", ["open parenthesis", "left parenthesis"]],
    [")", ["close parenthesis", "right parenthesis"]],
    ["-", ["hyphen", "dash", "minus/subtract"]],
    ["_", ["underscore", "understrike"]],
    ["=", ["equals"]],
    ["+", ["plus", "addition"]],
    ["[", ["open bracket", "left bracket"]],
    ["]", ["close bracket", "right bracket"]],
    ["{", ["open curly bracket", "left curly bracket"]],
    ["}", ["close curly bracket", "right curly bracket"]],
    ["|", ["pipe", "vertical bar", "vertical line", "broken bar"]],
    ["\\", ["backslash", "reverse slash"]],
    [";", ["semicolon"]],
    [":", ["colon"]],
    ["'", ["apostrophe", "single quote"]],
    ["\"", ["double quote"]],
    [",", ["comma"]],
    [".", ["period", "dot"]],
    ["<", ["open angle bracket", "less than", "left angle bracket"]],
    [">", ["close angel bracket", "greater than", "right angle bracket"]],
    ["/", ["forward slash"]],
    ["?", ["question mark"]]
]